### ISSUE TITLE
Plan v0.8.19

### ISSUE THREAD

**Issue by muga** [embulk/embulk#599]
- [x] CsvParserPlugin: Refresh the number of skipped header lines for each file https://github.com/embulk/embulk/pull/567
- [x] PreviewExecutor: Fix and avoid to call SamplingPageOutput#finish twice https://github.com/embulk/embulk/pull/571
- [x] Update snakeyaml to v1.18 https://github.com/embulk/embulk/pull/575
- [x] Update liquid to v4.0.0 https://github.com/embulk/embulk/pull/587
- [x] Change temporary filename format for Windows safe https://github.com/embulk/embulk/pull/589
- [x] Remove lib/embulk/command/embulk_generate_bin.rb that is not called anywhere https://github.com/embulk/embulk/pull/578 
- [x] Avoid saving unexpected string values saving to stringReferences https://github.com/embulk/embulk/pull/598
- [x] PreviewExecutor: Make sample size configurable https://github.com/embulk/embulk/pull/572 (https://github.com/embulk/embulk/issues/594 as well)
- [x] embulk/guess/csv.rb: it should fail if CSV parser cannot parse sample_lines https://github.com/embulk/embulk/pull/556

**Comment by muga** [comment]
@dmikurube any other items?

**Comment by dmikurube** [comment]
- [ ] Embulk versions in Java: #560 #597 
- [ ] Java-based subcommands: #558 #563 #568 #569 

Also, what do you think #585?

**Comment by muga** [comment]
okay, let's add it.

- [ ] Follow link if path prefix is symlink #585

**Comment by muga** [comment]
I start preparing v0.8.19.

**Comment by muga** [comment]
Working on https://github.com/embulk/embulk/pull/614

**Comment by muga** [comment]
Closed.
