### ISSUE TITLE
Plan 0.8.21

### ISSUE THREAD

**Issue by muga** [embulk/embulk#624]
- [x] Use Ruby's Embulk::VERSION_INTERNAL to fix #625. #626
- [x] Downgrade liquid 4.0.0 to 3.0.6 to fix regression #627. #632
- [x] Update msgpack in embulk.gemspec. #623

**Comment by muga** [comment]
Preparing 0.8.21 on https://github.com/embulk/embulk/pull/633
