### ISSUE TITLE
Plan 0.8.23

### ISSUE THREAD

**Issue by muga** [embulk/embulk#662]
- [x] PageReader#get{String,Timestamp,Json} calls #isNull to return null. #654
- [x] Ignore JsonParseException in JSON guess if JsonGuessPlugin could parse at least one JSON. #659
- [x] Ignore JsonParseException in JSON preview if at least one JSON is already parsed. #661

**Comment by hiroyuki-sato** [comment]
@muga Please check the following PR. (0.8.23 or later)

- [ ] Add clean illegal characters mode to json parser. #651 
- [ ] Add a note on the timestamp format in embulk-doc with a link to Ruby documents #648 (Doc only)
- [ ] Remove unnecessary error validations #646

And can you check the following issue? @civitaspo said It's a **Big Bug**

- [ ] JsonMappingException is raised when `taskSource.loadTask(PluginTask.class)` is called at `cleanup` method in Java FileOutputPlugin. #658

**Comment by dmikurube** [comment]
@hiroyuki-sato Sorry, this is a kind of maintenance release. They'll be cared in later releases.

**Comment by hiroyuki-sato** [comment]
@dmikurube OK Thanks. I updated previous comments.
Please merge #648 when you can (It's doc update only)

**Comment by dmikurube** [comment]
Released v0.8.23:

- https://bintray.com/embulk/maven/embulk/0.8.23
- https://rubygems.org/gems/embulk/versions/0.8.23
- https://github.com/embulk/embulk/releases/tag/v0.8.23
