### ISSUE TITLE
Plan 0.8.25

### ISSUE THREAD

**Issue by dmikurube** [embulk/embulk#673]
* [x] Prepare for JAR/Maven-based pure-Java plugins [#666] [#669]
* [x] Fix "could not find or load main class org.jruby.Main" when run as just "embulk" on Windows. [#676]
* [x] Fix "NameError: undefined local variable or method `bundle_path_index' for main:Object" when using Bundler. [#681]

**Comment by dmikurube** [comment]
Released!
